// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newConfessionComment(db *gorm.DB, opts ...gen.DOOption) confessionComment {
	_confessionComment := confessionComment{}

	_confessionComment.confessionCommentDo.UseDB(db, opts...)
	_confessionComment.confessionCommentDo.UseModel(&model.ConfessionComment{})

	tableName := _confessionComment.confessionCommentDo.TableName()
	_confessionComment.ALL = field.NewAsterisk(tableName)
	_confessionComment.ID = field.NewInt64(tableName, "id")
	_confessionComment.ConfessionID = field.NewInt64(tableName, "confession_id")
	_confessionComment.ParentCommentID = field.NewInt64(tableName, "parent_comment_id")
	_confessionComment.Username = field.NewString(tableName, "username")
	_confessionComment.ReplyToUsername = field.NewString(tableName, "reply_to_username")
	_confessionComment.Content = field.NewString(tableName, "content")
	_confessionComment.CreatedAt = field.NewTime(tableName, "created_at")
	_confessionComment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_confessionComment.DeletedAt = field.NewField(tableName, "deleted_at")

	_confessionComment.fillFieldMap()

	return _confessionComment
}

// confessionComment 表白评论表
type confessionComment struct {
	confessionCommentDo confessionCommentDo

	ALL             field.Asterisk
	ID              field.Int64  // 自增ID
	ConfessionID    field.Int64  // 表白ID
	ParentCommentID field.Int64  // 父评论ID，0表示一级评论
	Username        field.String // 评论用户名
	ReplyToUsername field.String // 被回复用户名
	Content         field.String // 评论内容
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间
	DeletedAt       field.Field  // 删除时间 (软删除)

	fieldMap map[string]field.Expr
}

func (c confessionComment) Table(newTableName string) *confessionComment {
	c.confessionCommentDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c confessionComment) As(alias string) *confessionComment {
	c.confessionCommentDo.DO = *(c.confessionCommentDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *confessionComment) updateTableName(table string) *confessionComment {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.ConfessionID = field.NewInt64(table, "confession_id")
	c.ParentCommentID = field.NewInt64(table, "parent_comment_id")
	c.Username = field.NewString(table, "username")
	c.ReplyToUsername = field.NewString(table, "reply_to_username")
	c.Content = field.NewString(table, "content")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *confessionComment) WithContext(ctx context.Context) IConfessionCommentDo {
	return c.confessionCommentDo.WithContext(ctx)
}

func (c confessionComment) TableName() string { return c.confessionCommentDo.TableName() }

func (c confessionComment) Alias() string { return c.confessionCommentDo.Alias() }

func (c confessionComment) Columns(cols ...field.Expr) gen.Columns {
	return c.confessionCommentDo.Columns(cols...)
}

func (c *confessionComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *confessionComment) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["confession_id"] = c.ConfessionID
	c.fieldMap["parent_comment_id"] = c.ParentCommentID
	c.fieldMap["username"] = c.Username
	c.fieldMap["reply_to_username"] = c.ReplyToUsername
	c.fieldMap["content"] = c.Content
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c confessionComment) clone(db *gorm.DB) confessionComment {
	c.confessionCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c confessionComment) replaceDB(db *gorm.DB) confessionComment {
	c.confessionCommentDo.ReplaceDB(db)
	return c
}

type confessionCommentDo struct{ gen.DO }

type IConfessionCommentDo interface {
	gen.SubQuery
	Debug() IConfessionCommentDo
	WithContext(ctx context.Context) IConfessionCommentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConfessionCommentDo
	WriteDB() IConfessionCommentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConfessionCommentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConfessionCommentDo
	Not(conds ...gen.Condition) IConfessionCommentDo
	Or(conds ...gen.Condition) IConfessionCommentDo
	Select(conds ...field.Expr) IConfessionCommentDo
	Where(conds ...gen.Condition) IConfessionCommentDo
	Order(conds ...field.Expr) IConfessionCommentDo
	Distinct(cols ...field.Expr) IConfessionCommentDo
	Omit(cols ...field.Expr) IConfessionCommentDo
	Join(table schema.Tabler, on ...field.Expr) IConfessionCommentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConfessionCommentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConfessionCommentDo
	Group(cols ...field.Expr) IConfessionCommentDo
	Having(conds ...gen.Condition) IConfessionCommentDo
	Limit(limit int) IConfessionCommentDo
	Offset(offset int) IConfessionCommentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConfessionCommentDo
	Unscoped() IConfessionCommentDo
	Create(values ...*model.ConfessionComment) error
	CreateInBatches(values []*model.ConfessionComment, batchSize int) error
	Save(values ...*model.ConfessionComment) error
	First() (*model.ConfessionComment, error)
	Take() (*model.ConfessionComment, error)
	Last() (*model.ConfessionComment, error)
	Find() ([]*model.ConfessionComment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfessionComment, err error)
	FindInBatches(result *[]*model.ConfessionComment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConfessionComment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConfessionCommentDo
	Assign(attrs ...field.AssignExpr) IConfessionCommentDo
	Joins(fields ...field.RelationField) IConfessionCommentDo
	Preload(fields ...field.RelationField) IConfessionCommentDo
	FirstOrInit() (*model.ConfessionComment, error)
	FirstOrCreate() (*model.ConfessionComment, error)
	FindByPage(offset int, limit int) (result []*model.ConfessionComment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConfessionCommentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c confessionCommentDo) Debug() IConfessionCommentDo {
	return c.withDO(c.DO.Debug())
}

func (c confessionCommentDo) WithContext(ctx context.Context) IConfessionCommentDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c confessionCommentDo) ReadDB() IConfessionCommentDo {
	return c.Clauses(dbresolver.Read)
}

func (c confessionCommentDo) WriteDB() IConfessionCommentDo {
	return c.Clauses(dbresolver.Write)
}

func (c confessionCommentDo) Session(config *gorm.Session) IConfessionCommentDo {
	return c.withDO(c.DO.Session(config))
}

func (c confessionCommentDo) Clauses(conds ...clause.Expression) IConfessionCommentDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c confessionCommentDo) Returning(value interface{}, columns ...string) IConfessionCommentDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c confessionCommentDo) Not(conds ...gen.Condition) IConfessionCommentDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c confessionCommentDo) Or(conds ...gen.Condition) IConfessionCommentDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c confessionCommentDo) Select(conds ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c confessionCommentDo) Where(conds ...gen.Condition) IConfessionCommentDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c confessionCommentDo) Order(conds ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c confessionCommentDo) Distinct(cols ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c confessionCommentDo) Omit(cols ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c confessionCommentDo) Join(table schema.Tabler, on ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c confessionCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c confessionCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c confessionCommentDo) Group(cols ...field.Expr) IConfessionCommentDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c confessionCommentDo) Having(conds ...gen.Condition) IConfessionCommentDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c confessionCommentDo) Limit(limit int) IConfessionCommentDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c confessionCommentDo) Offset(offset int) IConfessionCommentDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c confessionCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConfessionCommentDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c confessionCommentDo) Unscoped() IConfessionCommentDo {
	return c.withDO(c.DO.Unscoped())
}

func (c confessionCommentDo) Create(values ...*model.ConfessionComment) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c confessionCommentDo) CreateInBatches(values []*model.ConfessionComment, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c confessionCommentDo) Save(values ...*model.ConfessionComment) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c confessionCommentDo) First() (*model.ConfessionComment, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfessionComment), nil
	}
}

func (c confessionCommentDo) Take() (*model.ConfessionComment, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfessionComment), nil
	}
}

func (c confessionCommentDo) Last() (*model.ConfessionComment, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfessionComment), nil
	}
}

func (c confessionCommentDo) Find() ([]*model.ConfessionComment, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConfessionComment), err
}

func (c confessionCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfessionComment, err error) {
	buf := make([]*model.ConfessionComment, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c confessionCommentDo) FindInBatches(result *[]*model.ConfessionComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c confessionCommentDo) Attrs(attrs ...field.AssignExpr) IConfessionCommentDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c confessionCommentDo) Assign(attrs ...field.AssignExpr) IConfessionCommentDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c confessionCommentDo) Joins(fields ...field.RelationField) IConfessionCommentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c confessionCommentDo) Preload(fields ...field.RelationField) IConfessionCommentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c confessionCommentDo) FirstOrInit() (*model.ConfessionComment, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfessionComment), nil
	}
}

func (c confessionCommentDo) FirstOrCreate() (*model.ConfessionComment, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfessionComment), nil
	}
}

func (c confessionCommentDo) FindByPage(offset int, limit int) (result []*model.ConfessionComment, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c confessionCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c confessionCommentDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c confessionCommentDo) Delete(models ...*model.ConfessionComment) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *confessionCommentDo) withDO(do gen.Dao) *confessionCommentDo {
	c.DO = *do.(*gen.DO)
	return c
}
