// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	Confession *confession
	FileRecord *fileRecord
	User       *user
	UserBlock  *userBlock
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Confession = &Q.Confession
	FileRecord = &Q.FileRecord
	User = &Q.User
	UserBlock = &Q.UserBlock
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		Confession: newConfession(db, opts...),
		FileRecord: newFileRecord(db, opts...),
		User:       newUser(db, opts...),
		UserBlock:  newUserBlock(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Confession confession
	FileRecord fileRecord
	User       user
	UserBlock  userBlock
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Confession: q.Confession.clone(db),
		FileRecord: q.FileRecord.clone(db),
		User:       q.User.clone(db),
		UserBlock:  q.UserBlock.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Confession: q.Confession.replaceDB(db),
		FileRecord: q.FileRecord.replaceDB(db),
		User:       q.User.replaceDB(db),
		UserBlock:  q.UserBlock.replaceDB(db),
	}
}

type queryCtx struct {
	Confession IConfessionDo
	FileRecord IFileRecordDo
	User       IUserDo
	UserBlock  IUserBlockDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Confession: q.Confession.WithContext(ctx),
		FileRecord: q.FileRecord.WithContext(ctx),
		User:       q.User.WithContext(ctx),
		UserBlock:  q.UserBlock.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
