// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newUserBlock(db *gorm.DB, opts ...gen.DOOption) userBlock {
	_userBlock := userBlock{}

	_userBlock.userBlockDo.UseDB(db, opts...)
	_userBlock.userBlockDo.UseModel(&model.UserBlock{})

	tableName := _userBlock.userBlockDo.TableName()
	_userBlock.ALL = field.NewAsterisk(tableName)
	_userBlock.ID = field.NewInt64(tableName, "id")
	_userBlock.BlockerID = field.NewInt64(tableName, "blocker_id")
	_userBlock.BlockedID = field.NewInt64(tableName, "blocked_id")
	_userBlock.CreatedAt = field.NewTime(tableName, "created_at")
	_userBlock.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userBlock.fillFieldMap()

	return _userBlock
}

// userBlock 用户拉黑关系表
type userBlock struct {
	userBlockDo userBlockDo

	ALL       field.Asterisk
	ID        field.Int64 // 自增ID
	BlockerID field.Int64 // 拉黑发起人ID
	BlockedID field.Int64 // 被拉黑用户ID
	CreatedAt field.Time  // 创建时间
	UpdatedAt field.Time  // 更新时间

	fieldMap map[string]field.Expr
}

func (u userBlock) Table(newTableName string) *userBlock {
	u.userBlockDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userBlock) As(alias string) *userBlock {
	u.userBlockDo.DO = *(u.userBlockDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userBlock) updateTableName(table string) *userBlock {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.BlockerID = field.NewInt64(table, "blocker_id")
	u.BlockedID = field.NewInt64(table, "blocked_id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userBlock) WithContext(ctx context.Context) IUserBlockDo {
	return u.userBlockDo.WithContext(ctx)
}

func (u userBlock) TableName() string { return u.userBlockDo.TableName() }

func (u userBlock) Alias() string { return u.userBlockDo.Alias() }

func (u userBlock) Columns(cols ...field.Expr) gen.Columns { return u.userBlockDo.Columns(cols...) }

func (u *userBlock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userBlock) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["id"] = u.ID
	u.fieldMap["blocker_id"] = u.BlockerID
	u.fieldMap["blocked_id"] = u.BlockedID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userBlock) clone(db *gorm.DB) userBlock {
	u.userBlockDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userBlock) replaceDB(db *gorm.DB) userBlock {
	u.userBlockDo.ReplaceDB(db)
	return u
}

type userBlockDo struct{ gen.DO }

type IUserBlockDo interface {
	gen.SubQuery
	Debug() IUserBlockDo
	WithContext(ctx context.Context) IUserBlockDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserBlockDo
	WriteDB() IUserBlockDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserBlockDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserBlockDo
	Not(conds ...gen.Condition) IUserBlockDo
	Or(conds ...gen.Condition) IUserBlockDo
	Select(conds ...field.Expr) IUserBlockDo
	Where(conds ...gen.Condition) IUserBlockDo
	Order(conds ...field.Expr) IUserBlockDo
	Distinct(cols ...field.Expr) IUserBlockDo
	Omit(cols ...field.Expr) IUserBlockDo
	Join(table schema.Tabler, on ...field.Expr) IUserBlockDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserBlockDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserBlockDo
	Group(cols ...field.Expr) IUserBlockDo
	Having(conds ...gen.Condition) IUserBlockDo
	Limit(limit int) IUserBlockDo
	Offset(offset int) IUserBlockDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBlockDo
	Unscoped() IUserBlockDo
	Create(values ...*model.UserBlock) error
	CreateInBatches(values []*model.UserBlock, batchSize int) error
	Save(values ...*model.UserBlock) error
	First() (*model.UserBlock, error)
	Take() (*model.UserBlock, error)
	Last() (*model.UserBlock, error)
	Find() ([]*model.UserBlock, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBlock, err error)
	FindInBatches(result *[]*model.UserBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserBlock) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserBlockDo
	Assign(attrs ...field.AssignExpr) IUserBlockDo
	Joins(fields ...field.RelationField) IUserBlockDo
	Preload(fields ...field.RelationField) IUserBlockDo
	FirstOrInit() (*model.UserBlock, error)
	FirstOrCreate() (*model.UserBlock, error)
	FindByPage(offset int, limit int) (result []*model.UserBlock, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserBlockDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userBlockDo) Debug() IUserBlockDo {
	return u.withDO(u.DO.Debug())
}

func (u userBlockDo) WithContext(ctx context.Context) IUserBlockDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userBlockDo) ReadDB() IUserBlockDo {
	return u.Clauses(dbresolver.Read)
}

func (u userBlockDo) WriteDB() IUserBlockDo {
	return u.Clauses(dbresolver.Write)
}

func (u userBlockDo) Session(config *gorm.Session) IUserBlockDo {
	return u.withDO(u.DO.Session(config))
}

func (u userBlockDo) Clauses(conds ...clause.Expression) IUserBlockDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userBlockDo) Returning(value interface{}, columns ...string) IUserBlockDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userBlockDo) Not(conds ...gen.Condition) IUserBlockDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userBlockDo) Or(conds ...gen.Condition) IUserBlockDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userBlockDo) Select(conds ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userBlockDo) Where(conds ...gen.Condition) IUserBlockDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userBlockDo) Order(conds ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userBlockDo) Distinct(cols ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userBlockDo) Omit(cols ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userBlockDo) Join(table schema.Tabler, on ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userBlockDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userBlockDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userBlockDo) Group(cols ...field.Expr) IUserBlockDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userBlockDo) Having(conds ...gen.Condition) IUserBlockDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userBlockDo) Limit(limit int) IUserBlockDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userBlockDo) Offset(offset int) IUserBlockDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userBlockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBlockDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userBlockDo) Unscoped() IUserBlockDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userBlockDo) Create(values ...*model.UserBlock) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userBlockDo) CreateInBatches(values []*model.UserBlock, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userBlockDo) Save(values ...*model.UserBlock) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userBlockDo) First() (*model.UserBlock, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBlock), nil
	}
}

func (u userBlockDo) Take() (*model.UserBlock, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBlock), nil
	}
}

func (u userBlockDo) Last() (*model.UserBlock, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBlock), nil
	}
}

func (u userBlockDo) Find() ([]*model.UserBlock, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserBlock), err
}

func (u userBlockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBlock, err error) {
	buf := make([]*model.UserBlock, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userBlockDo) FindInBatches(result *[]*model.UserBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userBlockDo) Attrs(attrs ...field.AssignExpr) IUserBlockDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userBlockDo) Assign(attrs ...field.AssignExpr) IUserBlockDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userBlockDo) Joins(fields ...field.RelationField) IUserBlockDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userBlockDo) Preload(fields ...field.RelationField) IUserBlockDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userBlockDo) FirstOrInit() (*model.UserBlock, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBlock), nil
	}
}

func (u userBlockDo) FirstOrCreate() (*model.UserBlock, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBlock), nil
	}
}

func (u userBlockDo) FindByPage(offset int, limit int) (result []*model.UserBlock, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userBlockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userBlockDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userBlockDo) Delete(models ...*model.UserBlock) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userBlockDo) withDO(do gen.Dao) *userBlockDo {
	u.DO = *do.(*gen.DO)
	return u
}
