// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfession = "confessions"

// Confession 表白帖子主表
type Confession struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	SenderID     int64     `gorm:"column:sender_id;not null;comment:发送者ID" json:"sender_id"`                               // 发送者ID
	ReceiverName string    `gorm:"column:receiver_name;not null;comment:接收者昵称/姓名" json:"receiver_name"`                    // 接收者昵称/姓名
	Content      string    `gorm:"column:content;not null;comment:表白正文内容" json:"content"`                                  // 表白正文内容
	ImageURL     string    `gorm:"column:image_url;comment:图片外链(来自file_records表)" json:"image_url"`                        // 图片外链(来自file_records表)
	IsAnonymous  int8      `gorm:"column:is_anonymous;not null;comment:是否匿名: 0-公开, 1-匿名" json:"is_anonymous"`              // 是否匿名: 0-公开, 1-匿名
	Status       int8      `gorm:"column:status;not null;default:1;comment:状态: 1-正常显示, 2-审核中, 3-已删除" json:"status"`        // 状态: 1-正常显示, 2-审核中, 3-已删除
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Confession's table name
func (*Confession) TableName() string {
	return TableNameConfession
}
