// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameConfessionComment = "confession_comments"

// ConfessionComment 表白评论表
type ConfessionComment struct {
	ID           int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	ConfessionID int64                 `gorm:"column:confession_id;not null;comment:表白ID" json:"confession_id"`                        // 表白ID
	Username     string                `gorm:"column:username;not null;comment:评论用户名" json:"username"`                                 // 评论用户名
	Content      string                `gorm:"column:content;not null;comment:评论内容" json:"content"`                                    // 评论内容
	CreatedAt    time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time             `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:删除时间 (软删除);softDelete:milli" json:"-"`                // 删除时间 (软删除)
}

// TableName ConfessionComment's table name
func (*ConfessionComment) TableName() string {
	return TableNameConfessionComment
}
