// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileRecord = "file_records"

// FileRecord 文件去重记录表
type FileRecord struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	FileHash  string    `gorm:"column:file_hash;not null;comment:文件内容MD5指纹" json:"file_hash"`                           // 文件内容MD5指纹
	FileURL   string    `gorm:"column:file_url;not null;comment:七牛云完整外链" json:"file_url"`                               // 七牛云完整外链
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName FileRecord's table name
func (*FileRecord) TableName() string {
	return TableNameFileRecord
}
