// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserBlock = "user_blocks"

// UserBlock 用户拉黑关系表
type UserBlock struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	BlockerID int64     `gorm:"column:blocker_id;not null;comment:拉黑发起人ID" json:"blocker_id"`                           // 拉黑发起人ID
	BlockedID int64     `gorm:"column:blocked_id;not null;comment:被拉黑用户ID" json:"blocked_id"`                           // 被拉黑用户ID
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName UserBlock's table name
func (*UserBlock) TableName() string {
	return TableNameUserBlock
}
